version: '3.4'

services:
  subscription.webapi:
    image: ${DOCKER_REGISTRY-}subscriptionwebapi
    build:
      context: .
      dockerfile: Subscription.Service/Presentation/WebApi/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NewStrong!Password1"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    container_name: sqlpreview
    hostname: sqlpreview

